name: example
description: A sample command-line application as an example for kiwi.
version: 0.1.0
homepage: https://github.com/vanlooverenkoen/kiwi

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  kiwi: ^2.1.1

dev_dependencies:
  test: ^1.15.4
  build_runner: ^1.10.3
  kiwi_generator: ^2.1.1

dependency_overrides:
  kiwi:
    path: ../kiwi
  kiwi_generator:
    path: ../kiwi_generator