name: example
description: A sample command-line application as an example for kiwi.
version: 0.1.0
homepage: https://github.com/vanlooverenkoen/kiwi

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  kiwi: ^3.0.0

dev_dependencies:
  test: ^1.17.5
  build_runner: ^2.0.4
  kiwi_generator: ^3.0.0

dependency_overrides:
  kiwi:
    path: ../kiwi
  kiwi_generator:
    path: ../kiwi_generator