name: example
description: A sample command-line application as an example for kiwi.
version: 0.1.0
homepage: https://github.com/gbtb16/kiwi

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  kiwi: ^4.0.3

dev_dependencies:
  test: ^1.23.1
  build_runner: ^2.3.3
  kiwi_generator: ^4.0.3

dependency_overrides:
  kiwi:
    path: ../kiwi
  kiwi_generator:
    path: ../kiwi_generator