name: kiwi_generator
description: Generates dependency injection code using the kiwi package to reduce development time.
version: 4.3.0
homepage: https://github.com/gbtb16/kiwi/tree/master/packages/kiwi_generator
repository: https://github.com/gbtb16/kiwi/tree/master/packages/kiwi_generator
issue_tracker: https://github.com/gbtb16/kiwi/issues

environment:
  sdk: '>=2.14.0 <4.0.0'

dependencies:
  analyzer: ^8.1.1
  build: '>=3.0.0 <5.0.0'
  build_config: ^1.1.1
  built_collection: ^5.1.1
  code_builder: ^4.10.0
  dart_style: '>=2.3.7 <4.0.0'
  kiwi_generator:
    git:
      url: git@github.com:Doublon/kiwi.git
      path: packages/kiwi
      ref: temp
  path: ^1.8.3
  source_gen: '>=3.0.0 <5.0.0'

dev_dependencies:
  build_runner: ^2.5.0
  build_test: ^3.3.0
  test: ^1.25.1

topics:
  - kiwi
  - automatic-generator
  - dependency-injector