name: actions_tools
description: A sample command-line application as an example for kiwi.
version: 0.1.0
homepage: https://github.com/gbtb16/kiwi

environment:
  sdk: '>=2.14.0 <3.0.0'

dev_dependencies:
  test: ^1.23.1
  yaml: ^3.1.1
