name: flutter_example
description: A Flutter example for kiwi
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  kiwi: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  kiwi_generator: ^4.0.1

dependency_overrides:
  kiwi:
    path: ../kiwi/
  kiwi_generator:
    path: ../kiwi_generator/

flutter:
  uses-material-design: true