name: flutter_example
description: A Flutter example for kiwi
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  kiwi: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.5
  kiwi_generator: ^2.1.1

dependency_overrides:
  kiwi:
    path: ../kiwi/
  kiwi_generator:
    path: ../kiwi_generator/

flutter:
  uses-material-design: true