name: kiwi
description: A simple yet efficient IoC container for Dart and Flutter (can be coupled with the kiwi_generator package).
version: 0.3.1
homepage: https://github.com/vanlooverenkoen/kiwi/kiwi

environment:
  sdk: '>=2.2.0 <3.0.0'

dev_dependencies:
  test: ^1.14.7
