name: kiwi
description: A simple yet efficient dependency injection container for Dart and Flutter (can be coupled with the kiwi_generator package).
version: 2.1.1
homepage: https://github.com/vanlooverenkoen/kiwi/tree/master/kiwi

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  meta: ^1.2.3

dev_dependencies:
  test: ^1.15.4
