name: build_all

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk: [ stable, beta, dev ]
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Build & format for kiwi_generator
        run: |
          cd kiwi_generator
          flutter packages get
          flutter packages pub run build_runner build --delete-conflicting-outputs
          flutter format .
      - name: Build & format for example
        run: |
          cd example
          dart pub get
          flutter packages pub run build_runner build --delete-conflicting-outputs
          flutter format .
      - name: Build & format for flutter_example
        run: |
          cd flutter_example
          flutter packages get
          flutter packages pub run build_runner build --delete-conflicting-outputs
          flutter format .
      - uses: tj-actions/verify-changed-files@v13
      - name: Run step only when any of the above files change.
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          echo "Changed files: ${{ steps.verify-changed-files.outputs.changed_files }}"        

