name: changelog

on:
  push:
    branches: [ 'master', 'stable' ]
  pull_request:
    branches: [ 'master', 'stable' ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'
      - name: Check changelog
        run: |
         cd tools/actions
         dart pub get
         cd ../.. 
         dart run tools/actions/changelog_checker.dart