name: kiwi_generator

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'
      - run: cd kiwi_generator
      - run: dart pub get
      - run: dart analyze --fatal-infos --fatal-warnings .
      - run: dart format -o none --set-exit-if-changed .
      - run: dart pub run test
